server:
  port: 8081
  servlet:
    session:
      persistent: false
      timeout: 120s

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/hibiscus_db
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}

bank:
  rate:POSTGRES_PASSWORD
    url: http://api.currencylayer.com
    endpoint: /live
    access_key: 3cb2148e7f1e0c00f2e85dc26d283925 #should be located in .env file but time.............
