server:
  port: 8081
  servlet:
    session:
      persistent: false

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/hibiscus_db
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
