server:
  port: 8081
  servlet:
    session:
      persistent: false
      timeout: 120s

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibiscus_db
    password: abc123
    username: postgres
