server:
  port: 8443
  ssl:
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: pkcs12
    key-alias: ${KEY_ALIAS}
    key-password: ${KEY_PASSWORD}
  servlet:
    session:
      persistent: false
      timeout: 120s

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/hibiscus_db
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}

bank:
    url: http://api.currencylayer.com
    endpoint: /live
    access_key: 3cb2148e7f1e0c00f2e85dc26d283925 #should be located in .env file but time.............
